baseURL: "https://boranhan.github.io" 
title: Boran Han
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: News
          url: news/
          weight: 3 
        - name: Keywords
          url: tags/
          weight: 4
        - name: Archive
          url: archive/
          weight: 5

params:
    description: "Welcome to my page!"
    author: Boran Han
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true

    profileMode:
          enabled: true
          title: Boran Han
          subtitle: "I'm a scientist at AWS AI Research and Education Labs. I earned the Ph.D. degree from Harvard University under the guidance of <a href=\"https://zhuang.harvard.edu/\" target=\"_blank\" style=\"color:#8e7bd0\">Prof. Xiaowei Zhuang</a>. My research is published in esteemed journals such as *Science*, *Cell*, *Nature Communications*, and *Proceedings of the National Academy of Sciences*, or at top-tier conferences including *NeurIPS*, *ICCV*, and *ICML*. <br/><br/> My primary areas of focus include: (1) Foundations in Machine Learning (2) Multimodal Foundation Models and Generative AI (3) Natural Science Discoveries (4) Innovative Machine Learning Algorithm Development in Microscopy. (5) Remote Sensing Foundation Models for Sustainability.  <br/><br/> <img src="research.png" alt="research">"
          imageUrl: "Image.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: profile
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: News
              url: news/
            - name: Keywords
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: Email
          url: boranhan.dl@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Prwxh24AAAAJ&hl=en
        - name: LinkedIn
          url: https://www.linkedin.com/in/boran-han-ba753966/
        - name: GitHub
          url: https://github.com/boranhan
        - name: Twitter
          url: https://twitter.com/BoranHan1742511

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Boran Han"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
